# Generated by Django 2.2.10 on 2020-11-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20201122_2057'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='order',
        #     name='code',
        # ),
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
