# Generated by Django 2.2.10 on 2020-11-22 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20201122_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_ream',
        ),
        migrations.RemoveField(
            model_name='supplier_slip',
            name='total_ream',
        ),
        migrations.AddField(
            model_name='supplier_slip',
            name='code',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, default=0.0, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('o', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Order')),
            ],
        ),
    ]
