# Generated by Django 2.2.10 on 2020-11-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20201123_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.RemoveField(
            model_name='supplier_slip',
            name='code',
        ),
        migrations.AddField(
            model_name='order',
            name='qty',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='supplier_slip',
            name='qty',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
