# Generated by Django 2.2.10 on 2020-11-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20201123_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier_slip',
            old_name='total_money',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='debit_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_money',
        ),
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='final_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
