# Generated by Django 2.2.10 on 2020-11-23 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20201124_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_dena',
            old_name='amount',
            new_name='final_cost',
        ),
        migrations.RenameField(
            model_name='supplier_slip',
            old_name='debit_amount',
            new_name='final_cost',
        ),
    ]
