# Generated by Django 3.0.7 on 2020-11-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_orderdetails_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
