# Generated by Django 3.0.7 on 2020-11-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_auto_20201128_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
