# Generated by Django 3.0.7 on 2020-11-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20201128_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='itemno',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
