# Generated by Django 3.0.7 on 2020-11-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_orderdetails_itemno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0.0, null=True),
        ),
    ]
