# Generated by Django 3.0.7 on 2020-12-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_auto_20201130_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='o',
            new_name='order',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, default='Cash', max_length=20, null=True),
        ),
    ]
