# Generated by Django 3.0.7 on 2020-12-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_payment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qty',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
