# Generated by Django 3.0.7 on 2020-12-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_order_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(default='S', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='S', max_length=1, null=True),
        ),
    ]
