# Generated by Django 3.0.7 on 2020-12-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_product_wt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qty',
        ),
    ]
