# Generated by Django 3.0.7 on 2020-12-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_auto_20201206_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='making_charges',
            field=models.DecimalField(decimal_places=2, default=22.0, max_digits=10, null=True),
        ),
    ]
