# Generated by Django 3.0.7 on 2020-12-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_auto_20201206_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gold_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
